server:
  port: ${PORT:5005}
  servlet:
    context-path: /auth
spring:
  application:
    name: zs-service-certificateauthority
  redis:
    host: ${REDIS_HOST:119.96.128.98}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_POSSWORD:123456}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://119.96.128.98:33307/db1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



auth:
  tokenValiditySeconds: 86400  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
#  cookieDomain: 192.168.3.11
#  cookieDomain: 192.168.1.4
  cookieDomain: 119.96.128.98
  cookieMaxAge: -1


encrypt:
  key-store:
    location: classpath:/zs.keystore
    secret: zhanshengkeystore
    alias: zskey
    password: zhansheng

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
#      defaultZone: ${EUREKA_SERVER:http://192.168.1.13:50101/eureka/}
      defaultZone: ${EUREKA_SERVER:http://192.168.0.74:50101/eureka/}
#      defaultZone: ${EUREKA_SERVER:http://192.168.1.4:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
#    ip-address: ${IP_ADDR ESS:192.168.1.13}
    ip-address: ${IP_ADDR ESS:119.96.128.98}
#    ip-address: ${IP_ADDR ESS:192.168.1.4}
    instance-id: ${spring.application.name}:${server.port} #指定实例id


