server:
  port: ${PORT:50101} #服务端口  port环境变量 port默认端口50010
spring:
  application:
    name: zs-govern-center #指定服务名
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://192.168.0.74:50101/eureka/,http://192.168.0.74:50102/eureka/}
#  119.96.128.98          defaultZone: ${EUREKA_SERVER:http://192.168.1.4:50101/eureka/,http://192.168.1.4:50102/eureka/}
#            defaultZone: ${EUREKA_SERVER:http://192.168.1.13:50101/eureka/,http://192.168.1.13:50102/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01} # 主机名

#shdq.whchance.com   39.104.91.245